// Helper function to click on buttons '2+2=' and check result
export const typeShortExpression = () => {
	cy.get('button')
		.contains('2')
		.click()
	cy.get('button')
		.contains('+')
		.click()
	cy.get('button')
		.contains('2')
		.click()
	cy.get('button')
		.contains('=')
		.click()
}

// Helper function to click on buttons '.2+2(.1-1*2)='
export const typeLongExpression = () => {
	cy.get('button')
		.contains('.')
		.click()
	cy.get('button')
		.contains('2')
		.click()
	cy.get('button')
		.contains('+')
		.click()
	cy.get('button')
		.contains('2')
		.click()
	cy.get('button')
		.contains('(')
		.click()
	cy.get('button')
		.contains('.')
		.click()
	cy.get('button')
		.contains('1')
		.click()
	cy.get('button')
		.contains('-')
		.click()
	cy.get('button')
		.contains('1')
		.click()
	cy.get('button')
		.contains('*')
		.click()
	cy.get('button')
		.contains('2')
		.click()
	cy.get('button')
		.contains(')')
		.click()
	cy.get('button')
		.contains('=')
		.click()
}
